<<<<<<< HEAD
title: Julien Lachaise
tagline: test github

=======
title : Julien Lachaise
tagline : test github
author :
	name : Julien Lachaise
	email : ju.lachaise@gmail.com
>>>>>>> c6b3d21722b6e700aa59f5d9db0af693ddc25ce6
